name: Basic CI

# Triggers for push to main/master branches and pull requests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v4
    
    # Set up Python 3.11 (single version for basic CI)
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install pytest and coverage for testing
        pip install pytest pytest-cov
        # Install project dependencies if requirements.txt exists
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        # Install project in development mode if setup.py or pyproject.toml exists
        if [ -f setup.py ]; then pip install -e .; fi
        if [ -f pyproject.toml ]; then pip install -e .; fi
    
    # Run tests with pytest and generate coverage report
    - name: Run tests with coverage
      run: |
        # Run pytest with coverage reporting
        pytest --cov=. --cov-report=xml --cov-report=term-missing
    
    # Upload coverage reports to Codecov (optional but commonly used)
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false