name: Dependency Update

on:
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:
    inputs:
      update_type:
        description: 'Type of update to perform'
        required: false
        default: 'all'
        type: choice
        options:
          - all
          - security
          - requirements

permissions:
  contents: write
  pull-requests: write
  security-events: write

jobs:
  dependency-scan:
    name: Scan Dependencies
    runs-on: ubuntu-latest
    outputs:
      vulnerabilities-found: ${{ steps.safety-check.outputs.vulnerabilities-found }}
      outdated-packages: ${{ steps.pip-check.outputs.outdated-count }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt', '**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install safety pip-audit pipdeptree pip-tools
          
          # Install project dependencies if they exist
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          elif [ -f pyproject.toml ]; then
            pip install -e .
          fi
      
      - name: Security vulnerability scan with Safety
        id: safety-check
        run: |
          echo "Running Safety security scan..."
          if safety check --json --output safety-report.json; then
            echo "vulnerabilities-found=false" >> $GITHUB_OUTPUT
            echo "âœ… No security vulnerabilities found"
          else
            echo "vulnerabilities-found=true" >> $GITHUB_OUTPUT
            echo "âš ï¸ Security vulnerabilities detected"
            safety check --short-report
          fi
        continue-on-error: true
      
      - name: Security audit with pip-audit
        run: |
          echo "Running pip-audit security scan..."
          pip-audit --format=json --output=pip-audit-report.json || true
          pip-audit --format=cyclonedx-json --output=sbom.json || true
        continue-on-error: true
      
      - name: Check for outdated packages
        id: pip-check
        run: |
          echo "Checking for outdated packages..."
          outdated_count=$(pip list --outdated --format=json | jq length)
          echo "outdated-count=$outdated_count" >> $GITHUB_OUTPUT
          echo "Found $outdated_count outdated packages"
          
          if [ $outdated_count -gt 0 ]; then
            echo "Outdated packages:"
            pip list --outdated
          fi
      
      - name: Generate dependency tree
        run: |
          echo "Generating dependency tree..."
          pipdeptree --json-tree > dependency-tree.json
          pipdeptree --graph-output png > dependency-graph.png || true
      
      - name: Upload security reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: security-reports
          path: |
            safety-report.json
            pip-audit-report.json
            sbom.json
            dependency-tree.json
            dependency-graph.png
          retention-days: 30

  license-compliance:
    name: License Compliance Check
    runs-on: ubuntu-latest
    needs: dependency-scan
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install license checking tools
        run: |
          python -m pip install --upgrade pip
          pip install pip-licenses licensecheck
      
      - name: Install project dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          elif [ -f pyproject.toml ]; then
            pip install -e .
          fi
      
      - name: Generate license report
        run: |
          echo "Generating license compliance report..."
          
          # Generate detailed license report
          pip-licenses --format=json --output-file=licenses.json
          pip-licenses --format=csv --output-file=licenses.csv
          pip-licenses --format=html --output-file=licenses.html
          
          # Check for problematic licenses
          echo "Checking for problematic licenses..."
          pip-licenses --format=plain --allow-only="MIT;BSD;Apache;ISC;MPL-2.0;LGPL" || true
      
      - name: License compatibility check
        run: |
          echo "Performing license compatibility analysis..."
          
          # Define incompatible licenses (customize as needed)
          INCOMPATIBLE_LICENSES="GPL-3.0;AGPL;SSPL"
          
          # Check for incompatible licenses
          if pip-licenses --format=json | jq -r '.[].License' | grep -E "$INCOMPATIBLE_LICENSES"; then
            echo "âš ï¸ Found potentially incompatible licenses"
            exit 1
          else
            echo "âœ… No license compatibility issues found"
          fi
        continue-on-error: true
      
      - name: Upload license reports
        uses: actions/upload-artifact@v3
        with:
          name: license-reports
          path: |
            licenses.json
            licenses.csv
            licenses.html
          retention-days: 30

  update-requirements:
    name: Update Requirements
    runs-on: ubuntu-latest
    needs: [dependency-scan, license-compliance]
    if: github.event.inputs.update_type == 'all' || github.event.inputs.update_type == 'requirements' || github.event_name == 'schedule'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install pip-tools
        run: |
          python -m pip install --upgrade pip
          pip install pip-tools
      
      - name: Update requirements files
        run: |
          echo "Updating requirements files..."
          
          # Update requirements.txt if it exists
          if [ -f requirements.in ]; then
            echo "Updating from requirements.in..."
            pip-compile --upgrade requirements.in
          elif [ -f requirements.txt ]; then
            echo "Generating requirements.in from requirements.txt..."
            # Create requirements.in from existing requirements.txt (remove version pins)
            sed 's/==.*//' requirements.txt > requirements.in
            pip-compile --upgrade requirements.in
          fi
          
          # Update development requirements if they exist
          if [ -f requirements-dev.in ]; then
            echo "Updating development requirements..."
            pip-compile --upgrade requirements-dev.in
          fi
          
          # Update test requirements if they exist
          if [ -f requirements-test.in ]; then
            echo "Updating test requirements..."
            pip-compile --upgrade requirements-test.in
          fi
      
      - name: Generate updated dependency report
        run: |
          echo "Generating updated dependency report..."
          
          # Install updated dependencies
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          
          # Generate new dependency tree
          pip install pipdeptree
          pipdeptree > updated-dependency-tree.txt
          pipdeptree --json-tree > updated-dependency-tree.json
      
      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet; then
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "No dependency updates available"
          else
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "Dependency updates available"
            git diff --name-only
          fi
      
      - name: Create Pull Request
        if: steps.changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: |
            chore: update dependencies
            
            - Updated requirements files with latest compatible versions
            - Performed security vulnerability scan
            - Verified license compliance
            
            Auto-generated by dependency-update workflow
          title: 'chore: automated dependency updates'
          body: |
            ## Automated Dependency Updates
            
            This PR contains automated dependency updates generated by the dependency-update workflow.
            
            ### Changes Made
            - âœ… Updated requirements files with latest compatible versions
            - âœ… Performed security vulnerability scan
            - âœ… Verified license compliance
            - âœ… Generated updated dependency tree
            
            ### Security Status
            - Vulnerabilities found: ${{ needs.dependency-scan.outputs.vulnerabilities-found }}
            - Outdated packages: ${{ needs.dependency-scan.outputs.outdated-packages }}
            
            ### Review Checklist
            - [ ] Review updated dependency versions
            - [ ] Check for breaking changes in updated packages
            - [ ] Verify all tests pass
            - [ ] Review security scan results
            - [ ] Confirm license compliance
            
            ### Artifacts
            Security reports and dependency analysis are available in the workflow artifacts.
            
            ---
            *This PR was automatically created by the dependency-update workflow*
          branch: automated/dependency-updates
          delete-branch: true
          labels: |
            dependencies
            automated
            chore

  security-advisory:
    name: Security Advisory
    runs-on: ubuntu-latest
    needs: dependency-scan
    if: needs.dependency-scan.outputs.vulnerabilities-found == 'true'
    
    steps:
      - name: Download security reports
        uses: actions/download-artifact@v3
        with:
          name: security-reports
      
      - name: Create security issue
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            
            // Read safety report
            let vulnerabilities = [];
            try {
              const safetyReport = JSON.parse(fs.readFileSync('safety-report.json', 'utf8'));
              vulnerabilities = safetyReport;
            } catch (error) {
              console.log('Could not parse safety report:', error.message);
            }
            
            if (vulnerabilities.length > 0) {
              const issueBody = `
            ## ðŸš¨ Security Vulnerabilities Detected
            
            The automated dependency scan has detected security vulnerabilities in project dependencies.
            
            ### Vulnerabilities Found: ${vulnerabilities.length}
            
            ${vulnerabilities.map(vuln => `
            #### ${vuln.package_name} ${vuln.installed_version}
            - **Vulnerability ID**: ${vuln.vulnerability_id}
            - **Severity**: ${vuln.severity || 'Unknown'}
            - **Description**: ${vuln.advisory}
            - **Affected Versions**: ${vuln.vulnerable_spec}
            - **Safe Versions**: ${vuln.safe_versions || 'See advisory'}
            `).join('\n')}
            
            ### Recommended Actions
            1. Review the vulnerability details above
            2. Update affected packages to safe versions
            3. Test the application after updates
            4. Consider using \`pip-audit\` for additional scanning
            
            ### Automated Remediation
            A dependency update PR may be automatically created to address these vulnerabilities.
            
            ---
            *This issue was automatically created by the dependency-update workflow*
            `;
            
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: `ðŸš¨ Security vulnerabilities detected in dependencies`,
                body: issueBody,
                labels: ['security', 'dependencies', 'automated']
              });
            }