name: Build and Deploy Sphinx Documentation

# Triggers for documentation builds
on:
  push:
    branches: [ main, master ]
    paths:
      - 'docs/**'
      - '*.py'
      - '**/*.py'
      - 'pyproject.toml'
      - 'setup.py'
      - 'requirements.txt'
      - 'docs-requirements.txt'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'docs/**'
      - '*.py'
      - '**/*.py'
  workflow_dispatch:

# Set permissions for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build documentation job
  build-docs:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history for proper version detection
    
    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    
    # Install dependencies
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        # Install Sphinx and common extensions
        pip install sphinx sphinx-rtd-theme sphinx-autodoc-typehints
        # Install additional Sphinx extensions
        pip install sphinxcontrib-napoleon myst-parser
        # Install documentation-specific requirements if they exist
        if [ -f docs-requirements.txt ]; then pip install -r docs-requirements.txt; fi
        if [ -f docs/requirements.txt ]; then pip install -r docs/requirements.txt; fi
        # Install project dependencies
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        # Install project in development mode for API documentation
        if [ -f setup.py ]; then pip install -e .; fi
        if [ -f pyproject.toml ]; then pip install -e .; fi
    
    # Initialize Sphinx documentation if conf.py doesn't exist
    - name: Initialize Sphinx documentation
      run: |
        if [ ! -f docs/conf.py ]; then
          echo "Initializing Sphinx documentation..."
          mkdir -p docs
          cd docs
          sphinx-quickstart --quiet --project="${GITHUB_REPOSITORY##*/}" \
            --author="$(git log --format='%an' | head -1)" \
            --release="1.0.0" \
            --language="en" \
            --suffix=".rst" \
            --master="index" \
            --ext-autodoc \
            --ext-viewcode \
            --ext-todo \
            --ext-coverage \
            --ext-imgmath \
            --ext-mathjax \
            --ext-ifconfig \
            --ext-githubpages \
            --no-makefile \
            --no-batchfile \
            .
          
          # Configure conf.py for better defaults
          cat >> conf.py << 'EOF'

# Additional configuration for better documentation
import os
import sys
sys.path.insert(0, os.path.abspath('..'))

# Theme configuration
html_theme = 'sphinx_rtd_theme'
html_theme_options = {
    'canonical_url': '',
    'analytics_id': '',
    'logo_only': False,
    'display_version': True,
    'prev_next_buttons_location': 'bottom',
    'style_external_links': False,
    'collapse_navigation': True,
    'sticky_navigation': True,
    'navigation_depth': 4,
    'includehidden': True,
    'titles_only': False
}

# Extension configuration
autodoc_default_options = {
    'members': True,
    'member-order': 'bysource',
    'special-members': '__init__',
    'undoc-members': True,
    'exclude-members': '__weakref__'
}

# Napoleon settings for Google/NumPy style docstrings
napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = False
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = False
napoleon_use_admonition_for_notes = False
napoleon_use_admonition_for_references = False
napoleon_use_ivar = False
napoleon_use_param = True
napoleon_use_rtype = True

# Add any paths that contain custom static files (such as style sheets)
html_static_path = ['_static']
EOF
          
          # Create a basic index.rst if it doesn't exist
          if [ ! -f index.rst ]; then
            cat > index.rst << EOF
Welcome to ${GITHUB_REPOSITORY##*/}'s documentation!
================================================

.. toctree::
   :maxdepth: 2
   :caption: Contents:

   modules

Indices and tables
==================

* :ref:\`genindex\`
* :ref:\`modindex\`
* :ref:\`search\`
EOF
          fi
          
          cd ..
        fi
    
    # Generate API documentation from docstrings
    - name: Generate API documentation
      run: |
        cd docs
        # Generate module documentation automatically
        if [ -d "../$(basename $GITHUB_REPOSITORY)" ]; then
          sphinx-apidoc -o . ../$(basename $GITHUB_REPOSITORY) --force --separate
        else
          # Try to find Python packages in common locations
          for pkg in $(find .. -name "*.py" -path "*/[!.]*/[!_]*" | head -1 | xargs dirname | xargs basename); do
            if [ -d "../$pkg" ] && [ -f "../$pkg/__init__.py" ]; then
              sphinx-apidoc -o . ../$pkg --force --separate
              break
            fi
          done
        fi
    
    # Build Sphinx documentation
    - name: Build documentation
      run: |
        cd docs
        # Build HTML documentation
        sphinx-build -b html . _build/html -W --keep-going
        
        # Create .nojekyll file for GitHub Pages
        touch _build/html/.nojekyll
        
        # Create index.html redirect if needed
        if [ ! -f _build/html/index.html ]; then
          echo '<meta http-equiv="refresh" content="0; url=./html/">' > _build/html/index.html
        fi
    
    # Upload documentation artifacts
    - name: Upload documentation artifacts
      uses: actions/upload-artifact@v3
      with:
        name: sphinx-docs
        path: docs/_build/html/
        retention-days: 30
    
    # Setup Pages (only on main branch)
    - name: Setup Pages
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: actions/configure-pages@v3
    
    # Upload to GitHub Pages (only on main branch)
    - name: Upload to GitHub Pages
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: actions/upload-pages-artifact@v2
      with:
        path: docs/_build/html/

  # Deploy to GitHub Pages job (only runs on main branch)
  deploy-pages:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-docs
    
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2